- project:
    templates:
      - check-requirements
      - horizon-nodejs4-jobs-nonvoting
      - horizon-nodejs10-jobs-nonvoting
      - designate-devstack-jobs
      - openstack-cover-jobs-horizon
      - openstack-lower-constraints-jobs
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - openstack-python36-jobs-horizon
      - openstack-python37-jobs-horizon
      - publish-openstack-docs-pti
    check:
      jobs:
        - horizon-openstack-tox-python3-django111
    gate:
      queue: designate
      jobs:
        - horizon-openstack-tox-python3-django111
