- project:
    templates:
      - designate-devstack-jobs
      - check-requirements
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - publish-openstack-sphinx-docs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
        - openstack-tox-cover:
            voting: false
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            voting: false
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            voting: false

    gate:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
