- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - horizon-nodejs14-jobs
      - openstack-cover-jobs-horizon
      - openstack-python3-yoga-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
